// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query"
import type { AxiosError } from "axios"

import { client } from "../client.gen"
import {
  getClassAssignmentsForStudent,
  getClassAssignmentsMy,
  getClassesMy,
  getProjectsMy,
  getTeachersClassStudentsPresence,
  type Options,
  postClassAssignmentsAssign,
  postClassAssignmentsByIdSubmit,
  postProjectsUpload,
  postStudentsLoginByQr,
  postStudentsMarkSeen,
  postTeachersLoginByPasscode,
  putProjectsByIdEdit,
} from "../sdk.gen"
import type {
  GetClassAssignmentsForStudentData,
  GetClassAssignmentsForStudentResponse,
  GetClassAssignmentsMyData,
  GetClassAssignmentsMyResponse,
  GetClassesMyData,
  GetClassesMyResponse,
  GetProjectsMyData,
  GetProjectsMyResponse,
  GetTeachersClassStudentsPresenceData,
  GetTeachersClassStudentsPresenceResponse,
  PostClassAssignmentsAssignData,
  PostClassAssignmentsAssignResponse,
  PostClassAssignmentsByIdSubmitData,
  PostClassAssignmentsByIdSubmitResponse,
  PostProjectsUploadData,
  PostProjectsUploadResponse,
  PostStudentsLoginByQrData,
  PostStudentsLoginByQrResponse,
  PostStudentsMarkSeenData,
  PostStudentsMarkSeenResponse,
  PostTeachersLoginByPasscodeData,
  PostTeachersLoginByPasscodeResponse,
  PutProjectsByIdEditData,
  PutProjectsByIdEditResponse,
} from "../types.gen"

/**
 * Login teacher by 6-digit passcode
 *
 * Return JWT + teacher + user (without secrets).
 */
export const postTeachersLoginByPasscodeMutation = (
  options?: Partial<Options<PostTeachersLoginByPasscodeData>>,
): UseMutationOptions<
  PostTeachersLoginByPasscodeResponse,
  AxiosError<DefaultError>,
  Options<PostTeachersLoginByPasscodeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostTeachersLoginByPasscodeResponse,
    AxiosError<DefaultError>,
    Options<PostTeachersLoginByPasscodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postTeachersLoginByPasscode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getTeachersClassStudentsPresenceQueryKey = (
  options: Options<GetTeachersClassStudentsPresenceData>,
) => createQueryKey("getTeachersClassStudentsPresence", options)

/**
 * Poll students presence in a class
 *
 * Return students in a class with computed presence status based on last_seen_at. Requires teacher JWT.
 */
export const getTeachersClassStudentsPresenceOptions = (
  options: Options<GetTeachersClassStudentsPresenceData>,
) =>
  queryOptions<
    GetTeachersClassStudentsPresenceResponse,
    AxiosError<DefaultError>,
    GetTeachersClassStudentsPresenceResponse,
    ReturnType<typeof getTeachersClassStudentsPresenceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeachersClassStudentsPresence({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTeachersClassStudentsPresenceQueryKey(options),
  })

/**
 * Login student by QR token
 *
 * Accept token (or qr_token). Return JWT + student + user (without secrets).
 */
export const postStudentsLoginByQrMutation = (
  options?: Partial<Options<PostStudentsLoginByQrData>>,
): UseMutationOptions<
  PostStudentsLoginByQrResponse,
  AxiosError<DefaultError>,
  Options<PostStudentsLoginByQrData>
> => {
  const mutationOptions: UseMutationOptions<
    PostStudentsLoginByQrResponse,
    AxiosError<DefaultError>,
    Options<PostStudentsLoginByQrData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postStudentsLoginByQr({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Mark student as recently active (last seen) or offline (best-effort)
 *
 * Update student.last_seen_at (throttled by server, e.g. once per 30 seconds). If status="offline", server forces last_seen_at older than threshold so presence becomes offline immediately.
 */
export const postStudentsMarkSeenMutation = (
  options?: Partial<Options<PostStudentsMarkSeenData>>,
): UseMutationOptions<
  PostStudentsMarkSeenResponse,
  AxiosError<DefaultError>,
  Options<PostStudentsMarkSeenData>
> => {
  const mutationOptions: UseMutationOptions<
    PostStudentsMarkSeenResponse,
    AxiosError<DefaultError>,
    Options<PostStudentsMarkSeenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postStudentsMarkSeen({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getClassesMyQueryKey = (options?: Options<GetClassesMyData>) =>
  createQueryKey("getClassesMy", options)

/**
 * List classes of current teacher (active academic year only, paginated)
 *
 * Return classes assigned to the currently authenticated teacher, restricted to the tenant's ACTIVE academic year. Supports pagination for infinite scroll. Stop fetching when `page >= meta.pagination.pageCount` or when `data.length === 0`.
 */
export const getClassesMyOptions = (options?: Options<GetClassesMyData>) =>
  queryOptions<
    GetClassesMyResponse,
    AxiosError<DefaultError>,
    GetClassesMyResponse,
    ReturnType<typeof getClassesMyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getClassesMy({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getClassesMyQueryKey(options),
  })

/**
 * Upload a project (.sjr + optional thumbnail) and create Project record
 *
 * Multipart upload endpoint. Server detects owner_type based on authenticated user: teacher -> owner_type=teacher, otherwise student -> owner_type=student. Stores media in S3/localstack via Strapi upload provider.
 */
export const postProjectsUploadMutation = (
  options?: Partial<Options<PostProjectsUploadData>>,
): UseMutationOptions<
  PostProjectsUploadResponse,
  AxiosError<DefaultError>,
  Options<PostProjectsUploadData>
> => {
  const mutationOptions: UseMutationOptions<
    PostProjectsUploadResponse,
    AxiosError<DefaultError>,
    Options<PostProjectsUploadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postProjectsUpload({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getProjectsMyQueryKey = (options?: Options<GetProjectsMyData>) =>
  createQueryKey("getProjectsMy", options)

/**
 * List projects of current user
 *
 * Teacher gets teacher-owned projects, student gets student-owned projects. Supports pagination via pagination[page] & pagination[pageSize].
 */
export const getProjectsMyOptions = (options?: Options<GetProjectsMyData>) =>
  queryOptions<
    GetProjectsMyResponse,
    AxiosError<DefaultError>,
    GetProjectsMyResponse,
    ReturnType<typeof getProjectsMyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectsMy({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getProjectsMyQueryKey(options),
  })

/**
 * Edit a project (multipart) - replace sjr_file/thumbnail and/or update fields
 *
 * Path param {id} is project documentId. Only project owner (teacher/student) can edit. If sjr_file is uploaded, project.sjr_file is replaced. Note: class-assignment snapshots (assigned_*) are not modified.
 */
export const putProjectsByIdEditMutation = (
  options?: Partial<Options<PutProjectsByIdEditData>>,
): UseMutationOptions<
  PutProjectsByIdEditResponse,
  AxiosError<DefaultError>,
  Options<PutProjectsByIdEditData>
> => {
  const mutationOptions: UseMutationOptions<
    PutProjectsByIdEditResponse,
    AxiosError<DefaultError>,
    Options<PutProjectsByIdEditData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putProjectsByIdEdit({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Teacher assigns 1..n teacher projects to 1 class
 *
 * Body contains class documentId and an array of teacher project documentIds. Server validates: class belongs to teacher, class is in active academic year, projects belong to teacher (owner_type=teacher). Server snapshots assigned_sjr_file/assigned_title/assigned_thumbnail at assign time so later project edits do not affect students.
 */
export const postClassAssignmentsAssignMutation = (
  options?: Partial<Options<PostClassAssignmentsAssignData>>,
): UseMutationOptions<
  PostClassAssignmentsAssignResponse,
  AxiosError<DefaultError>,
  Options<PostClassAssignmentsAssignData>
> => {
  const mutationOptions: UseMutationOptions<
    PostClassAssignmentsAssignResponse,
    AxiosError<DefaultError>,
    Options<PostClassAssignmentsAssignData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postClassAssignmentsAssign({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getClassAssignmentsMyQueryKey = (options?: Options<GetClassAssignmentsMyData>) =>
  createQueryKey("getClassAssignmentsMy", options)

/**
 * Teacher lists class assignments they created
 *
 * Optional query: ?class=<classDocumentId> to filter. Supports pagination via pagination[page] & pagination[pageSize]. Returns snapshot fields assigned_* to show what was assigned at the time.
 */
export const getClassAssignmentsMyOptions = (options?: Options<GetClassAssignmentsMyData>) =>
  queryOptions<
    GetClassAssignmentsMyResponse,
    AxiosError<DefaultError>,
    GetClassAssignmentsMyResponse,
    ReturnType<typeof getClassAssignmentsMyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getClassAssignmentsMy({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getClassAssignmentsMyQueryKey(options),
  })

export const getClassAssignmentsForStudentQueryKey = (
  options?: Options<GetClassAssignmentsForStudentData>,
) => createQueryKey("getClassAssignmentsForStudent", options)

/**
 * Student lists assignments for their class
 *
 * Returns class assignments where class = student's current class. Student must use assigned_sjr_file (snapshot) instead of project.sjr_file. Supports pagination via pagination[page] & pagination[pageSize].
 */
export const getClassAssignmentsForStudentOptions = (
  options?: Options<GetClassAssignmentsForStudentData>,
) =>
  queryOptions<
    GetClassAssignmentsForStudentResponse,
    AxiosError<DefaultError>,
    GetClassAssignmentsForStudentResponse,
    ReturnType<typeof getClassAssignmentsForStudentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getClassAssignmentsForStudent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getClassAssignmentsForStudentQueryKey(options),
  })

/**
 * Student submits a project to a class assignment
 *
 * Path param {id} is class-assignment documentId. Body contains student project documentId. Server validates class membership and project ownership (owner_type=student). Upserts submission by (student + class_assignment).
 */
export const postClassAssignmentsByIdSubmitMutation = (
  options?: Partial<Options<PostClassAssignmentsByIdSubmitData>>,
): UseMutationOptions<
  PostClassAssignmentsByIdSubmitResponse,
  AxiosError<DefaultError>,
  Options<PostClassAssignmentsByIdSubmitData>
> => {
  const mutationOptions: UseMutationOptions<
    PostClassAssignmentsByIdSubmitResponse,
    AxiosError<DefaultError>,
    Options<PostClassAssignmentsByIdSubmitData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postClassAssignmentsByIdSubmit({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
