// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  GetClassAssignmentsForStudentData,
  GetClassAssignmentsForStudentErrors,
  GetClassAssignmentsForStudentResponses,
  GetClassAssignmentsMyData,
  GetClassAssignmentsMyErrors,
  GetClassAssignmentsMyResponses,
  GetClassesMyData,
  GetClassesMyErrors,
  GetClassesMyResponses,
  GetProjectsMyData,
  GetProjectsMyErrors,
  GetProjectsMyResponses,
  GetTeachersClassStudentsPresenceData,
  GetTeachersClassStudentsPresenceErrors,
  GetTeachersClassStudentsPresenceResponses,
  PostClassAssignmentsAssignData,
  PostClassAssignmentsAssignErrors,
  PostClassAssignmentsAssignResponses,
  PostClassAssignmentsByIdSubmitData,
  PostClassAssignmentsByIdSubmitErrors,
  PostClassAssignmentsByIdSubmitResponses,
  PostProjectsUploadData,
  PostProjectsUploadErrors,
  PostProjectsUploadResponses,
  PostStudentsLoginByQrData,
  PostStudentsLoginByQrErrors,
  PostStudentsLoginByQrResponses,
  PostStudentsMarkSeenData,
  PostStudentsMarkSeenErrors,
  PostStudentsMarkSeenResponses,
  PostTeachersLoginByPasscodeData,
  PostTeachersLoginByPasscodeErrors,
  PostTeachersLoginByPasscodeResponses,
  PutProjectsByIdEditData,
  PutProjectsByIdEditErrors,
  PutProjectsByIdEditResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Login teacher by 6-digit passcode
 *
 * Return JWT + teacher + user (without secrets).
 */
export const postTeachersLoginByPasscode = <ThrowOnError extends boolean = false>(
  options: Options<PostTeachersLoginByPasscodeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostTeachersLoginByPasscodeResponses,
    PostTeachersLoginByPasscodeErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/teachers/login-by-passcode",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Poll students presence in a class
 *
 * Return students in a class with computed presence status based on last_seen_at. Requires teacher JWT.
 */
export const getTeachersClassStudentsPresence = <ThrowOnError extends boolean = false>(
  options: Options<GetTeachersClassStudentsPresenceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTeachersClassStudentsPresenceResponses,
    GetTeachersClassStudentsPresenceErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/teachers/class-students-presence",
    ...options,
  })

/**
 * Login student by QR token
 *
 * Accept token (or qr_token). Return JWT + student + user (without secrets).
 */
export const postStudentsLoginByQr = <ThrowOnError extends boolean = false>(
  options: Options<PostStudentsLoginByQrData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostStudentsLoginByQrResponses,
    PostStudentsLoginByQrErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/students/login-by-qr",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Mark student as recently active (last seen) or offline (best-effort)
 *
 * Update student.last_seen_at (throttled by server, e.g. once per 30 seconds). If status="offline", server forces last_seen_at older than threshold so presence becomes offline immediately.
 */
export const postStudentsMarkSeen = <ThrowOnError extends boolean = false>(
  options?: Options<PostStudentsMarkSeenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostStudentsMarkSeenResponses,
    PostStudentsMarkSeenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/students/mark-seen",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * List classes of current teacher (active academic year only, paginated)
 *
 * Return classes assigned to the currently authenticated teacher, restricted to the tenant's ACTIVE academic year. Supports pagination for infinite scroll. Stop fetching when `page >= meta.pagination.pageCount` or when `data.length === 0`.
 */
export const getClassesMy = <ThrowOnError extends boolean = false>(
  options?: Options<GetClassesMyData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetClassesMyResponses, GetClassesMyErrors, ThrowOnError>({
    responseType: "json",
    url: "/classes/my",
    ...options,
  })

/**
 * Upload a project (.sjr + optional thumbnail) and create Project record
 *
 * Multipart upload endpoint. Server detects owner_type based on authenticated user: teacher -> owner_type=teacher, otherwise student -> owner_type=student. Stores media in S3/localstack via Strapi upload provider.
 */
export const postProjectsUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostProjectsUploadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostProjectsUploadResponses,
    PostProjectsUploadErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    url: "/projects/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * List projects of current user
 *
 * Teacher gets teacher-owned projects, student gets student-owned projects. Supports pagination via pagination[page] & pagination[pageSize].
 */
export const getProjectsMy = <ThrowOnError extends boolean = false>(
  options?: Options<GetProjectsMyData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetProjectsMyResponses, GetProjectsMyErrors, ThrowOnError>({
    responseType: "json",
    url: "/projects/my",
    ...options,
  })

/**
 * Edit a project (multipart) - replace sjr_file/thumbnail and/or update fields
 *
 * Path param {id} is project documentId. Only project owner (teacher/student) can edit. If sjr_file is uploaded, project.sjr_file is replaced. Note: class-assignment snapshots (assigned_*) are not modified.
 */
export const putProjectsByIdEdit = <ThrowOnError extends boolean = false>(
  options: Options<PutProjectsByIdEditData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutProjectsByIdEditResponses,
    PutProjectsByIdEditErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    url: "/projects/{id}/edit",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Teacher assigns 1..n teacher projects to 1 class
 *
 * Body contains class documentId and an array of teacher project documentIds. Server validates: class belongs to teacher, class is in active academic year, projects belong to teacher (owner_type=teacher). Server snapshots assigned_sjr_file/assigned_title/assigned_thumbnail at assign time so later project edits do not affect students.
 */
export const postClassAssignmentsAssign = <ThrowOnError extends boolean = false>(
  options: Options<PostClassAssignmentsAssignData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostClassAssignmentsAssignResponses,
    PostClassAssignmentsAssignErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/class-assignments/assign",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Teacher lists class assignments they created
 *
 * Optional query: ?class=<classDocumentId> to filter. Supports pagination via pagination[page] & pagination[pageSize]. Returns snapshot fields assigned_* to show what was assigned at the time.
 */
export const getClassAssignmentsMy = <ThrowOnError extends boolean = false>(
  options?: Options<GetClassAssignmentsMyData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetClassAssignmentsMyResponses,
    GetClassAssignmentsMyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/class-assignments/my",
    ...options,
  })

/**
 * Student lists assignments for their class
 *
 * Returns class assignments where class = student's current class. Student must use assigned_sjr_file (snapshot) instead of project.sjr_file. Supports pagination via pagination[page] & pagination[pageSize].
 */
export const getClassAssignmentsForStudent = <ThrowOnError extends boolean = false>(
  options?: Options<GetClassAssignmentsForStudentData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetClassAssignmentsForStudentResponses,
    GetClassAssignmentsForStudentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/class-assignments/for-student",
    ...options,
  })

/**
 * Student submits a project to a class assignment
 *
 * Path param {id} is class-assignment documentId. Body contains student project documentId. Server validates class membership and project ownership (owner_type=student). Upserts submission by (student + class_assignment).
 */
export const postClassAssignmentsByIdSubmit = <ThrowOnError extends boolean = false>(
  options: Options<PostClassAssignmentsByIdSubmitData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostClassAssignmentsByIdSubmitResponses,
    PostClassAssignmentsByIdSubmitErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/class-assignments/{id}/submit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
