// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}

export type UserSafe = {
  /**
   * User id
   */
  id: number
  /**
   * User documentId
   */
  documentId: string
  username: string
  email: string
  provider?: string | null
  confirmed: boolean
  blocked: boolean
  phone?: string | null
  createdAt?: string
  updatedAt?: string
  publishedAt?: string | null
  locale?: string | null
  [key: string]:
    | unknown
    | number
    | string
    | string
    | string
    | null
    | boolean
    | string
    | null
    | string
    | string
    | null
    | string
    | null
    | undefined
}

export type TeacherLoginByPasscodeRequest = {
  /**
   * 6-digit passcode
   */
  passcode: string
}

export type TeacherLoginTeacher = {
  /**
   * Teacher internal numeric id
   */
  id: number
  /**
   * Teacher documentId (UUID)
   */
  documentId: string
  /**
   * Teacher name
   */
  name?: string | null
  /**
   * 6-digit passcode
   */
  passcode?: string | null
  [key: string]: unknown | number | string | string | null | string | null | undefined
}

export type TeacherLoginByPasscodeResponse = {
  /**
   * JWT token
   */
  jwt: string
  teacher: TeacherLoginTeacher
  user: UserSafe
}

/**
 * Presence computed from last_seen_age_seconds
 */
export type TeacherStudentPresenceStatus = "online" | "offline" | "unknown"

export type TeacherStudentPresenceItem = {
  id: number
  documentId: string
  name: string
  name_kana: string
  /**
   * UTC timestamp
   */
  last_seen_at: string | null
  /**
   * Seconds since last_seen_at (server computed)
   */
  last_seen_age_seconds: number | null
  presence_status: TeacherStudentPresenceStatus
}

export type Pagination = {
  /**
   * Current page (1-based).
   */
  page: number
  /**
   * Items per page.
   */
  pageSize: number
  /**
   * Total number of pages.
   */
  pageCount: number
  /**
   * Total number of items.
   */
  total: number
}

export type TeacherClassStudentsPresenceResponse = {
  data: Array<TeacherStudentPresenceItem>
  meta: {
    /**
     * Server time (UTC)
     */
    server_time: string
    presence: {
      online_threshold_seconds: number
      /**
       * Online students in the whole class (not paginated)
       */
      online_count: number
      /**
       * Total students in the whole class (not paginated)
       */
      total_count: number
    }
    pagination: Pagination
    class: {
      documentId: string
      name: string
    }
  }
}

export type StudentLoginByQrRequest = {
  /**
   * QR token (preferred field name)
   */
  token?: string
  /**
   * QR token (legacy field name)
   */
  qr_token?: string
}

export type StudentLoginStudent = {
  id: number
  documentId: string
  name: string
  name_kana: string
  qr_token: string
  users_permissions_user: UserSafe & unknown
  /**
   * Tenant school admin
   */
  school_admin: {
    id: number
    documentId: string
    name: string
  }
  /**
   * Student class (can be null)
   */
  class?: {
    id: number
    documentId: string
    name: string
  } | null
  [key: string]:
    | unknown
    | number
    | string
    | string
    | (UserSafe & unknown)
    | {
        id: number
        documentId: string
        name: string
      }
    | {
        id: number
        documentId: string
        name: string
      }
    | null
    | undefined
}

export type StudentLoginByQrResponse = {
  /**
   * JWT token
   */
  jwt: string
  student: StudentLoginStudent
}

export type StudentMarkSeenRequest = {
  /**
   * Optional presence hint. If omitted, defaults to "online". Use "offline" when app is backgrounded/logged out (best-effort).
   */
  status?: "online" | "offline"
}

export type StudentMarkSeenResponse = {
  /**
   * True if last_seen_at was updated in DB; false if throttled (e.g. called within 30s window). For status="offline", usually true.
   */
  updated: boolean
  /**
   * Effective status processed by server.
   */
  status: "online" | "offline"
}

export type MetaWithPagination = {
  pagination: Pagination
}

export type ClassMyAcademicYear = {
  /**
   * AcademicYear internal numeric id
   */
  id: number
  /**
   * AcademicYear documentId (UUID)
   */
  documentId: string
  /**
   * AcademicYear name
   */
  name: string
  [key: string]: unknown | number | string | string
}

export type ClassMyItem = {
  /**
   * Class internal numeric id
   */
  id: number
  /**
   * Class documentId (UUID)
   */
  documentId: string
  /**
   * Class name
   */
  name: string
  /**
   * Related academic year (populated).
   */
  academic_year?: {
    /**
     * AcademicYear internal numeric id
     */
    id: number
    /**
     * AcademicYear documentId (UUID)
     */
    documentId: string
    /**
     * AcademicYear name
     */
    name: string
    [key: string]: unknown | number | string | string
  } | null
  /**
   * Number of students currently assigned to this class
   */
  studentsCount: number
  [key: string]:
    | unknown
    | number
    | string
    | string
    | {
        /**
         * AcademicYear internal numeric id
         */
        id: number
        /**
         * AcademicYear documentId (UUID)
         */
        documentId: string
        /**
         * AcademicYear name
         */
        name: string
        [key: string]: unknown | number | string | string
      }
    | null
    | number
    | undefined
}

export type ClassMyResponse = {
  /**
   * Classes of the current teacher in the ACTIVE academic year only (paginated). If there is no active academic year, returns an empty array.
   */
  data: Array<ClassMyItem>
  meta: MetaWithPagination
}

/**
 * Pagination params for infinite scroll. Use querystring format only: `?pagination[page]=1&pagination[pageSize]=10`.
 */
export type ClassMyQuery = {
  /**
   * Page number (1-based). Default: 1
   */
  "pagination[page]"?: number
  /**
   * Items per page. Default: 10. Max: 100
   */
  "pagination[pageSize]"?: number
}

export type UploadFile = {
  /**
   * Upload file internal numeric id
   */
  id: number
  /**
   * Upload file documentId
   */
  documentId: string
  /**
   * Original file name
   */
  name: string
  /**
   * File extension
   */
  ext?: string | null
  /**
   * MIME type
   */
  mime?: string | null
  /**
   * File size reported by upload plugin (often KB, may be float)
   */
  size: number
  /**
   * Public URL (built using baseUrl) or origin URL
   */
  url: string
  /**
   * Upload provider name
   */
  provider?: string
  createdAt?: string
  updatedAt?: string
  [key: string]: unknown | number | string | string | null | string | null | number | undefined
}

/**
 * Who owns the project
 */
export type ProjectOwnerType = "teacher" | "student"

export type ProjectTeacher = {
  id: number
  documentId: string
  name: string
  [key: string]: unknown | number | string
}

export type ProjectStudent = {
  id: number
  documentId: string
  name: string
  [key: string]: unknown | number | string
}

export type ProjectItem = {
  /**
   * Project internal numeric id
   */
  id: number
  /**
   * Project documentId
   */
  documentId: string
  /**
   * Project title
   */
  title: string
  description?: string | null
  owner_type: ProjectOwnerType & unknown
  /**
   * File size in bytes (integer).
   */
  file_size?: number | null
  createdAt: string
  updatedAt: string
  publishedAt?: string | null
  sjr_file: UploadFile & unknown
  /**
   * Thumbnail (optional)
   */
  thumbnail?: {
    /**
     * Upload file internal numeric id
     */
    id: number
    /**
     * Upload file documentId
     */
    documentId: string
    /**
     * Original file name
     */
    name: string
    /**
     * File extension
     */
    ext?: string | null
    /**
     * MIME type
     */
    mime?: string | null
    /**
     * File size reported by upload plugin (often KB, may be float)
     */
    size: number
    /**
     * Public URL (built using baseUrl) or origin URL
     */
    url: string
    /**
     * Upload provider name
     */
    provider?: string
    createdAt?: string
    updatedAt?: string
    [key: string]: unknown | number | string | string | null | string | null | number | undefined
  } | null
  /**
   * Populated when owner_type=teacher
   */
  teacher?: {
    id: number
    documentId: string
    name: string
    [key: string]: unknown | number | string
  } | null
  /**
   * Populated when owner_type=student
   */
  student?: {
    id: number
    documentId: string
    name: string
    [key: string]: unknown | number | string
  } | null
  [key: string]:
    | unknown
    | number
    | string
    | string
    | null
    | (ProjectOwnerType & unknown)
    | number
    | null
    | string
    | null
    | (UploadFile & unknown)
    | {
        /**
         * Upload file internal numeric id
         */
        id: number
        /**
         * Upload file documentId
         */
        documentId: string
        /**
         * Original file name
         */
        name: string
        /**
         * File extension
         */
        ext?: string | null
        /**
         * MIME type
         */
        mime?: string | null
        /**
         * File size reported by upload plugin (often KB, may be float)
         */
        size: number
        /**
         * Public URL (built using baseUrl) or origin URL
         */
        url: string
        /**
         * Upload provider name
         */
        provider?: string
        createdAt?: string
        updatedAt?: string
        [key: string]:
          | unknown
          | number
          | string
          | string
          | null
          | string
          | null
          | number
          | undefined
      }
    | null
    | {
        id: number
        documentId: string
        name: string
        [key: string]: unknown | number | string
      }
    | null
    | {
        id: number
        documentId: string
        name: string
        [key: string]: unknown | number | string
      }
    | null
    | undefined
}

export type ProjectUploadResponse = {
  data: ProjectItem & unknown
}

export type ProjectEditResponse = {
  data: ProjectItem & unknown
}

export type ProjectsMyResponse = {
  /**
   * List projects owned by current user (teacher or student)
   */
  data: Array<ProjectItem>
  meta: MetaWithPagination
}

export type ProjectEditMultipart = {
  /**
   * New project title (optional)
   */
  title?: string
  /**
   * New project description (optional)
   */
  description?: string
  /**
   * .sjr file (optional). If provided, replaces current sjr_file
   */
  sjr_file?: Blob | File
  /**
   * thumbnail (optional). If provided, replaces current thumbnail
   */
  thumbnail?: Blob | File
}

export type ProjectUploadMultipart = {
  /**
   * Project title
   */
  title: string
  description?: string
  /**
   * .sjr file (required)
   */
  sjr_file?: Blob | File
  /**
   * thumbnail (optional)
   */
  thumbnail?: Blob | File
}

export type UploadFileCa = {
  id: number
  documentId: string
  name: string
  url: string
  size: number
  [key: string]: unknown | number | string | number
}

export type ClassLite = {
  id: number
  documentId: string
  name: string
  [key: string]: unknown | number | string
}

export type TeacherLite = {
  id: number
  documentId: string
  name: string
  [key: string]: unknown | number | string
}

export type ProjectLite = {
  id: number
  documentId: string
  title: string
  /**
   * Project thumbnail (optional)
   */
  thumbnail?: {
    id: number
    documentId: string
    name: string
    url: string
    size: number
    [key: string]: unknown | number | string | number
  } | null
  /**
   * Project sjr file (optional populate). NOTE: students should use assigned_sjr_file from class-assignment (snapshot) instead.
   */
  sjr_file?: {
    id: number
    documentId: string
    name: string
    url: string
    size: number
    [key: string]: unknown | number | string | number
  } | null
  [key: string]:
    | unknown
    | number
    | string
    | {
        id: number
        documentId: string
        name: string
        url: string
        size: number
        [key: string]: unknown | number | string | number
      }
    | null
    | {
        id: number
        documentId: string
        name: string
        url: string
        size: number
        [key: string]: unknown | number | string | number
      }
    | null
    | undefined
}

export type ClassAssignmentItem = {
  id: number
  documentId: string
  assigned_at?: string | null
  assigned_title?: string | null
  assigned_sjr_file: UploadFileCa & unknown
  /**
   * Snapshot thumbnail at assign time (optional)
   */
  assigned_thumbnail?: {
    id: number
    documentId: string
    name: string
    url: string
    size: number
    [key: string]: unknown | number | string | number
  } | null
  createdAt?: string
  updatedAt?: string
  class: ClassLite & unknown
  project: ProjectLite & unknown
  teacher?: TeacherLite & unknown
  [key: string]:
    | unknown
    | number
    | string
    | string
    | null
    | string
    | null
    | (UploadFileCa & unknown)
    | {
        id: number
        documentId: string
        name: string
        url: string
        size: number
        [key: string]: unknown | number | string | number
      }
    | null
    | (ClassLite & unknown)
    | (ProjectLite & unknown)
    | (TeacherLite & unknown)
    | undefined
}

export type ClassAssignmentItemStudent = {
  id: number
  documentId: string
  assigned_at?: string | null
  assigned_title?: string | null
  createdAt?: string
  updatedAt?: string
  class: ClassLite & unknown
  teacher?: TeacherLite & unknown
  assigned_sjr_file: UploadFileCa & unknown
  /**
   * Snapshot thumbnail at assign time (optional)
   */
  assigned_thumbnail?: {
    id: number
    documentId: string
    name: string
    url: string
    size: number
    [key: string]: unknown | number | string | number
  } | null
  [key: string]:
    | unknown
    | number
    | string
    | string
    | null
    | string
    | null
    | (ClassLite & unknown)
    | (TeacherLite & unknown)
    | (UploadFileCa & unknown)
    | {
        id: number
        documentId: string
        name: string
        url: string
        size: number
        [key: string]: unknown | number | string | number
      }
    | null
    | undefined
}

export type ClassAssignmentAssignRequest = {
  /**
   * Class documentId
   */
  class: string
  /**
   * Teacher project documentIds
   */
  projectIds: Array<string>
}

export type ClassAssignmentAssignResponse = {
  /**
   * Created or existing class-assignment rows (duplicates skipped)
   */
  data: Array<ClassAssignmentItem>
}

export type MyClassAssignmentsResponse = {
  data: Array<ClassAssignmentItem>
  meta: MetaWithPagination & unknown
}

export type StudentClassAssignmentsResponse = {
  /**
   * Assignments for student's current class (uses snapshot fields assigned_*)
   */
  data: Array<ClassAssignmentItemStudent>
  meta: MetaWithPagination & unknown
}

export type ClassAssignmentSubmitRequest = {
  /**
   * Student project documentId to submit
   */
  project: string
}

export type AssignmentSubmissionItem = {
  id: number
  documentId: string
  submitted_at?: string | null
  /**
   * Populated student (shape depends on your populate)
   */
  student?: unknown
  /**
   * Populated class-assignment (optional; includes assigned_* snapshot fields)
   */
  class_assignment?: unknown
  /**
   * Populated submitted project (optional)
   */
  project?: unknown
  [key: string]: unknown | number | string | string | null | undefined
}

export type ClassAssignmentSubmitResponse = {
  data: AssignmentSubmissionItem & unknown
}

export type PostTeachersLoginByPasscodeData = {
  body: TeacherLoginByPasscodeRequest
  path?: never
  query?: never
  url: "/teachers/login-by-passcode"
}

export type PostTeachersLoginByPasscodeErrors = {
  /**
   * `passcode` must be 6 digits
   */
  400: unknown
  /**
   * Invalid passcode / User is blocked
   */
  401: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PostTeachersLoginByPasscodeResponses = {
  /**
   * Successful login
   */
  200: TeacherLoginByPasscodeResponse
}

export type PostTeachersLoginByPasscodeResponse =
  PostTeachersLoginByPasscodeResponses[keyof PostTeachersLoginByPasscodeResponses]

export type GetTeachersClassStudentsPresenceData = {
  body?: never
  path?: never
  query: {
    /**
     * Class documentId
     */
    "class": string
    /**
     * Online threshold in seconds (default 120).
     */
    "online_threshold"?: string | number
    /**
     * Page (1-based).
     */
    "pagination[page]"?: string | number
    /**
     * Page size.
     */
    "pagination[pageSize]"?: string | number
  }
  url: "/teachers/class-students-presence"
}

export type GetTeachersClassStudentsPresenceErrors = {
  /**
   * Invalid query (missing/invalid class documentId)
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Not allowed (teacher not linked to class / tenant mismatch)
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type GetTeachersClassStudentsPresenceResponses = {
  /**
   * OK
   */
  200: TeacherClassStudentsPresenceResponse
}

export type GetTeachersClassStudentsPresenceResponse =
  GetTeachersClassStudentsPresenceResponses[keyof GetTeachersClassStudentsPresenceResponses]

export type PostStudentsLoginByQrData = {
  body: StudentLoginByQrRequest
  path?: never
  query?: never
  url: "/students/login-by-qr"
}

export type PostStudentsLoginByQrErrors = {
  /**
   * `token` is required
   */
  400: unknown
  /**
   * Invalid QR / User is blocked
   */
  401: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PostStudentsLoginByQrResponses = {
  /**
   * Successful login
   */
  200: StudentLoginByQrResponse
}

export type PostStudentsLoginByQrResponse =
  PostStudentsLoginByQrResponses[keyof PostStudentsLoginByQrResponses]

export type PostStudentsMarkSeenData = {
  body?: StudentMarkSeenRequest
  path?: never
  query?: never
  url: "/students/mark-seen"
}

export type PostStudentsMarkSeenErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Student not found
   */
  404: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PostStudentsMarkSeenResponses = {
  /**
   * OK
   */
  200: StudentMarkSeenResponse
}

export type PostStudentsMarkSeenResponse =
  PostStudentsMarkSeenResponses[keyof PostStudentsMarkSeenResponses]

export type GetClassesMyData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (1-based). Default: 1
     */
    "pagination[page]"?: number
    /**
     * Items per page. Default: 10. Max: 100
     */
    "pagination[pageSize]"?: number
  }
  url: "/classes/my"
}

export type GetClassesMyErrors = {
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (authenticated user is not linked to a teacher record, or teacher has no tenant school_admin link).
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type GetClassesMyResponses = {
  /**
   * Successful response
   */
  200: ClassMyResponse
}

export type GetClassesMyResponse = GetClassesMyResponses[keyof GetClassesMyResponses]

export type PostProjectsUploadData = {
  body: ProjectUploadMultipart
  path?: never
  query?: never
  url: "/projects/upload"
}

export type PostProjectsUploadErrors = {
  /**
   * ValidationError (missing title/sjr_file, invalid payload)
   */
  400: unknown
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (user is not linked to teacher/student record)
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PostProjectsUploadResponses = {
  /**
   * Created project
   */
  200: ProjectUploadResponse
}

export type PostProjectsUploadResponse =
  PostProjectsUploadResponses[keyof PostProjectsUploadResponses]

export type GetProjectsMyData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (>=1). Default 1.
     */
    "pagination[page]"?: string | number
    /**
     * Items per page (1..100). Default 10.
     */
    "pagination[pageSize]"?: string | number
  }
  url: "/projects/my"
}

export type GetProjectsMyErrors = {
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (user is not linked to teacher/student record)
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type GetProjectsMyResponses = {
  /**
   * Successful response
   */
  200: ProjectsMyResponse
}

export type GetProjectsMyResponse = GetProjectsMyResponses[keyof GetProjectsMyResponses]

export type PutProjectsByIdEditData = {
  body: ProjectEditMultipart
  path: {
    /**
     * Project documentId
     */
    id: string
  }
  query?: never
  url: "/projects/{id}/edit"
}

export type PutProjectsByIdEditErrors = {
  /**
   * ValidationError (nothing to update / invalid payload)
   */
  400: unknown
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (not owner)
   */
  403: unknown
  /**
   * Project not found
   */
  404: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PutProjectsByIdEditResponses = {
  /**
   * Updated project
   */
  200: ProjectEditResponse
}

export type PutProjectsByIdEditResponse =
  PutProjectsByIdEditResponses[keyof PutProjectsByIdEditResponses]

export type PostClassAssignmentsAssignData = {
  body: ClassAssignmentAssignRequest
  path?: never
  query?: never
  url: "/class-assignments/assign"
}

export type PostClassAssignmentsAssignErrors = {
  /**
   * ValidationError (invalid class/projectIds, no active AY, etc.)
   */
  400: unknown
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (not a teacher, tenant mismatch, etc.)
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PostClassAssignmentsAssignResponses = {
  /**
   * Created/Existing class assignments
   */
  200: ClassAssignmentAssignResponse
}

export type PostClassAssignmentsAssignResponse =
  PostClassAssignmentsAssignResponses[keyof PostClassAssignmentsAssignResponses]

export type GetClassAssignmentsMyData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional class documentId filter
     */
    "class"?: string
    /**
     * Page number (>=1). Default 1.
     */
    "pagination[page]"?: string | number
    /**
     * Items per page (1..100). Default 10.
     */
    "pagination[pageSize]"?: string | number
  }
  url: "/class-assignments/my"
}

export type GetClassAssignmentsMyErrors = {
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (not a teacher)
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type GetClassAssignmentsMyResponses = {
  /**
   * Successful response
   */
  200: MyClassAssignmentsResponse
}

export type GetClassAssignmentsMyResponse =
  GetClassAssignmentsMyResponses[keyof GetClassAssignmentsMyResponses]

export type GetClassAssignmentsForStudentData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (>=1). Default 1.
     */
    "pagination[page]"?: string | number
    /**
     * Items per page (1..100). Default 10.
     */
    "pagination[pageSize]"?: string | number
  }
  url: "/class-assignments/for-student"
}

export type GetClassAssignmentsForStudentErrors = {
  /**
   * Student has no class
   */
  400: unknown
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (not a student)
   */
  403: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type GetClassAssignmentsForStudentResponses = {
  /**
   * Successful response
   */
  200: StudentClassAssignmentsResponse
}

export type GetClassAssignmentsForStudentResponse =
  GetClassAssignmentsForStudentResponses[keyof GetClassAssignmentsForStudentResponses]

export type PostClassAssignmentsByIdSubmitData = {
  body: ClassAssignmentSubmitRequest
  path: {
    /**
     * class-assignment documentId
     */
    id: string
  }
  query?: never
  url: "/class-assignments/{id}/submit"
}

export type PostClassAssignmentsByIdSubmitErrors = {
  /**
   * ValidationError (missing params/body, student has no class, invalid project, etc.)
   */
  400: unknown
  /**
   * Missing/invalid JWT (unauthorized)
   */
  401: unknown
  /**
   * Not allowed (not in class, not student, etc.)
   */
  403: unknown
  /**
   * Class assignment not found
   */
  404: unknown
  /**
   * Internal server error
   */
  500: unknown
}

export type PostClassAssignmentsByIdSubmitResponses = {
  /**
   * Created/updated submission
   */
  200: ClassAssignmentSubmitResponse
}

export type PostClassAssignmentsByIdSubmitResponse =
  PostClassAssignmentsByIdSubmitResponses[keyof PostClassAssignmentsByIdSubmitResponses]
